function [out] = med3(X)
%MED3 Apply the median filter on the given image by looking at the 3x3
%neighboohood

[row, col] = size(X);
tmp = 127 * ones(row+2, col+2, 'uint8');
for x=2: row+1
    for y=2: col+1
        tmp(x, y) = X(x-1, y-1);
    end
end

% apply filter
for x=2: row+1
    for y=2: col+1
        out(x-1, y-1) = median([ ...
              tmp(x-1, y-1); ...
              tmp(x-1, y); ...
              tmp(x-1, y+1); ...
              tmp(x, y-1); ...
              tmp(x, y); ...
              tmp(x, y+1); ...
              tmp(x+1, y-1); ...
              tmp(x+1, y); ...
              tmp(x+1, y+1)]);
    end
end
