% EL844 workshop 2 - bfrd2

function [out] = med5(X)
%MED5  Apply the median filter on the given image by looking at the 3x3
%neighboohood

% deal with the image edges by adding a border of 127 around the original
% matrix
[row, col] = size(X);
tmp = 127 * ones(row+4, col+4, 'uint8');
for x=3: row+2
    for y=3: col+2
        tmp(x, y) = X(x-2, y-2);
    end
end

% apply filter
for x=3: row+2
    for y=3: col+2
        out(x-2, y-2) = median([ ...
              tmp(x-2, y-2); ...
              tmp(x-2, y-1); ...
              tmp(x-2, y); ...
              tmp(x-2, y+1); ...
              tmp(x-2, y+2); ...
              tmp(x-1, y-2); ...
              tmp(x-1, y-1); ...
              tmp(x-1, y); ...
              tmp(x-1, y+1); ...
              tmp(x-1, y+2); ...
              tmp(x, y-2); ...
              tmp(x, y-1); ...
              tmp(x, y); ...
              tmp(x, y+1); ...
              tmp(x, y+2); ...
              tmp(x+1, y-2); ...
              tmp(x+1, y-1); ...
              tmp(x+1, y); ...
              tmp(x+1, y+1); ...
              tmp(x+1, y+2); ...
              tmp(x+2, y-2); ...
              tmp(x+2, y-1); ...
              tmp(x+2, y); ...
              tmp(x+2, y+1); ...
              tmp(x+2, y+2)]);
    end
end